"""Build (and optionally insert) the ``runs`` rows for the controlled experiments.

Usage (from the repo root):

    python -m api.persist_runs            # dry run: check rows, write runs_rows.json
    python -m api.persist_runs --write    # also insert them into Supabase

Which runs, and which one is best, come from the validation comparison written
by api.run_experiments (models/experiments/controlled_comparison.json): every
run in it gets a row, and only its validation winner is ``is_best``.

Rules enforced before anything is written:
  - each row has exactly the insertable columns of ``runs`` (001_init.sql)
  - the winner's run.json must already hold its final evaluation
    (python -m api.evaluate_final), with test, calibration, confusion-matrix,
    per-class and permutation-importance columns filled
  - every other run must be validation-only: its test/calibration columns stay
    NULL, because only the selected run is ever scored on test
  - exactly one row is ``is_best``; --write refuses names already in ``runs``
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import List, Optional, Sequence

from api.train import MODELS_DIR, _repo_relative

# Insertable columns of the runs table, in 001_init.sql order (id and
# created_at are generated by Postgres).
RUNS_COLUMNS = (
    "name", "architecture", "hidden_sizes", "activation", "dropout",
    "learning_rate", "weight_decay", "epochs", "best_epoch", "batch_size", "seed",
    "config",
    "train_loss", "val_loss", "val_accuracy", "val_roc_auc",
    "test_accuracy", "test_precision", "test_recall", "test_f1", "test_roc_auc",
    "calibration_method", "ece_before", "ece_after", "brier_before", "brier_after",
    "calibration_bins",
    "train_metrics", "val_metrics", "test_metrics",
    "confusion_matrix", "per_class_metrics", "permutation_importance",
    "checkpoint_path", "preprocessor_path", "is_best",
)
NOT_NULL_COLUMNS = (
    "name", "architecture", "hidden_sizes", "activation", "dropout", "learning_rate",
    "weight_decay", "epochs", "batch_size", "seed", "config",
    "train_metrics", "val_metrics", "test_metrics", "is_best",
)
# Filled only by the final evaluation of the selected run.
FINAL_EVALUATION_COLUMNS = (
    "test_accuracy", "test_precision", "test_recall", "test_f1", "test_roc_auc",
    "calibration_method", "ece_before", "ece_after", "brier_before", "brier_after",
    "calibration_bins", "confusion_matrix", "per_class_metrics", "permutation_importance",
)

DEFAULT_COMPARISON = MODELS_DIR / "experiments" / "controlled_comparison.json"
ROWS_FILENAME = "runs_rows.json"  # dry-run output, next to the comparison


# ---------------------------------------------------------------------------
# one row
# ---------------------------------------------------------------------------
def validate_run_row(row: dict) -> None:
    """Raise ValueError unless ``row`` can be inserted into ``runs`` as is."""
    problems = []
    missing = [c for c in RUNS_COLUMNS if c not in row]
    unknown = sorted(set(row) - set(RUNS_COLUMNS))
    if missing or unknown:
        problems.append(f"columns: missing {missing}, unknown {unknown}")
    else:
        nulls = [c for c in NOT_NULL_COLUMNS if row[c] is None]
        if nulls:
            problems.append(f"NOT NULL columns are null: {nulls}")
        if not isinstance(row["is_best"], bool):
            problems.append("is_best must be true or false")
        if not isinstance(row["hidden_sizes"], list) or len(row["hidden_sizes"]) < 2:
            problems.append("hidden_sizes needs at least 2 layers")
        cm = row["confusion_matrix"]
        if cm is not None and not (
                isinstance(cm, list) and len(cm) == 2
                and all(isinstance(r, list) and len(r) == 2 and all(isinstance(v, int) for v in r)
                        for r in cm)):
            problems.append("confusion_matrix must be [[TN, FP], [FN, TP]] integers")
        if row["is_best"]:
            unset = [c for c in FINAL_EVALUATION_COLUMNS if row[c] is None]
            if unset or not row["test_metrics"]:
                problems.append(f"the best run needs its final evaluation; unset: "
                                f"{unset + ([] if row['test_metrics'] else ['test_metrics'])}")
        try:
            json.dumps(row, allow_nan=False)
        except (TypeError, ValueError) as e:
            problems.append(f"not valid JSON for Supabase: {e}")
    if problems:
        name = row.get("name", "?")
        raise ValueError(f"run {name!r} does not fit the runs table:\n  - " + "\n  - ".join(problems))


def complete_run_row(row: dict) -> dict:
    """Return ``row`` with every runs column present (absent ones NULL), validated.

    A row from api.train.build_run_row (validation-only) gets NULL test,
    calibration and importance columns and ``is_best = false``.
    """
    unknown = sorted(set(row) - set(RUNS_COLUMNS))
    if unknown:
        raise ValueError(f"run {row.get('name', '?')!r} has columns not in runs: {unknown}")
    full = {c: row.get(c) for c in RUNS_COLUMNS}
    if full["test_metrics"] is None:
        full["test_metrics"] = {}
    if full["is_best"] is None:
        full["is_best"] = False
    validate_run_row(full)
    return full


# ---------------------------------------------------------------------------
# the controlled set
# ---------------------------------------------------------------------------
def read_comparison(path: Path = DEFAULT_COMPARISON) -> dict:
    path = Path(path)
    if not path.exists():
        raise ValueError(f"{path} not found; run api.run_experiments first")
    payload = json.loads(path.read_text())
    if payload.get("test_set_evaluated") is not False:
        raise ValueError(f"{path} must come from a validation-only comparison")
    return payload


def validation_winner(path: Path = DEFAULT_COMPARISON) -> str:
    """Name of the run selected on validation loss by api.run_experiments."""
    return read_comparison(path)["winner"]


def _has_final_evaluation(row: dict) -> bool:
    return bool(row.get("test_metrics")) or any(row.get(c) is not None for c in FINAL_EVALUATION_COLUMNS)


def build_controlled_rows(models_dir: Path, names: Sequence[str], best: str) -> List[dict]:
    """Complete rows for every run in ``names``; only ``best`` is ``is_best``.

    Reads models/<name>/run.json. Returns the non-best rows first (in the given
    order) and the best row last.
    """
    if len(set(names)) != len(names):
        raise ValueError(f"duplicate run names: {list(names)}")
    if best not in names:
        raise ValueError(f"best run {best!r} is not one of {list(names)}")
    others, best_row = [], None
    for name in names:
        path = Path(models_dir) / name / "run.json"
        if not path.exists():
            raise ValueError(f"{path} not found")
        raw = json.loads(path.read_text())
        if raw.get("name") != name:
            raise ValueError(f"{path} is for run {raw.get('name')!r}, not {name!r}")
        if name == best:
            if raw.get("is_best") is not True:
                raise ValueError(f"{path} has no final evaluation yet; run "
                                 f"`python -m api.evaluate_final --run {name}` first")
            best_row = complete_run_row(raw)
        else:
            if raw.get("is_best"):
                raise ValueError(f"{path} is marked is_best but {best!r} is the selected run")
            if _has_final_evaluation(raw):
                raise ValueError(f"{path} has test/calibration results, but only the "
                                 f"selected run ({best!r}) may be evaluated on test")
            others.append(complete_run_row({**raw, "is_best": False}))
    rows = others + [best_row]
    if sum(r["is_best"] for r in rows) != 1:
        raise ValueError("exactly one run must be is_best")
    return rows


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        description="Build the runs-table rows for the controlled experiments (dry run by default).")
    ap.add_argument("--comparison", default=str(DEFAULT_COMPARISON),
                    help="validation comparison from api.run_experiments")
    ap.add_argument("--models-dir", default=str(MODELS_DIR),
                    help="runs are read from <models-dir>/<name>/run.json")
    ap.add_argument("--write", action="store_true",
                    help="insert the rows into the Supabase runs table")
    return ap


def main(argv: Optional[List[str]] = None) -> None:
    args = build_parser().parse_args(argv)
    try:
        comparison = read_comparison(Path(args.comparison))
        names = [r["name"] for r in comparison["runs"]]
        rows = build_controlled_rows(Path(args.models_dir), names, comparison["winner"])
    except ValueError as e:
        raise SystemExit(str(e))

    for r in rows:
        test = "test evaluated" if r["test_metrics"] else "validation only"
        print(f"[row] {r['name']:<10} is_best={str(r['is_best']).lower():<5} "
              f"val_loss={r['val_loss']:.4f}  {test}")
    out_path = Path(args.comparison).parent / ROWS_FILENAME
    out_path.write_text(json.dumps(rows, indent=2, allow_nan=False))
    print(f"[saved] {_repo_relative(out_path)}")

    if not args.write:
        print("[runs] not written to Supabase (pass --write)")
        return

    from dotenv import load_dotenv

    from api import db
    from api.train import REPO_ROOT

    load_dotenv(REPO_ROOT / ".env")
    clash = sorted(set(db.fetch_run_names()) & {r["name"] for r in rows})
    if clash:
        raise SystemExit(f"runs already has rows named {clash}; delete them first or skip --write")
    for r in rows:  # best last, so a failure never leaves a best row without its peers
        saved = db.insert_training_run(r)
        print(f"[runs] inserted {r['name']} id={saved['id']} is_best={r['is_best']}")


if __name__ == "__main__":
    sys.exit(main())
